server:
  port: 8082

# Dubbo 广播方式配置
dubbo:
  application:
    name: ocean_lottery
    version: 1.0.0
  registry:
    #    address: zookeeper://127.0.0.1:2181
    address: multicast://224.5.6.8:1234
  protocol:
    name: dubbo
    port: 20880

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  #熔断超时时间
ribbon:
  ReadTimeout: 60000  #请求处理的超时时间
  ConnectTimeout: 60000 #请求连接超时时间
  MaxAutoRetries: 0 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数 1