server:
  port: 8082

# Dubbo 广播方式配置
dubbo:
  application:
    name: ocean_lottery
    version: 1.0.0
  registry:
    #    address: zookeeper://127.0.0.1:2181
    address: multicast://224.5.6.8:1234
  protocol:
    name: dubbo
    port: 20880